name: Release develop state

on:
  push:
    branches:
      - ftr-github-release-develop

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # fetch all history to include latest tags for build metadata
          submodules: 'recursive'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Frontend xar with Dockerfile
        run: |
          docker buildx build --target builder --load --platform linux/amd64,linux/arm64 -t edirom-online-frontend:develop -f Dockerfile .

     - name: Copy build-xar from image
        run: |
          container_id=$(docker create edirom-online-frontend:develop)
          mkdir -p build-xar
          docker cp "$container_id:/app/build-xar/." build-xar/
          docker rm "$container_id"
      
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: develop
          overwrite: true
          prerelease: true
          name: "Development build"
          body: "Automatic release from the develop branch."
          artifacts: build-xar/**/*